---
- name: Wait for ssh connection
  hosts: all
  gather_facts: False
  tasks:
    - name: Ensure SSH port is open
      wait_for:
        port: 22
        delay: 10
        timeout: 120
        host:  '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
      vars:
        ansible_connection: local

# Root will own the repo. If this is a problem, put the 
# clone task in a separate play without 'become: yes' 
# However, make sure the normal user has permission to 
# create the destination directory
- name: Clone git repo
  hosts: all
  become: yes # do these tasks as root 
  tasks:
  - name: Make sure git is installed
    vars:
      ansible_python_interpreter: /usr/bin/python
    yum:
      name: 
        - git
      state: latest
      update_cache: yes
  - name: Clone repo
    ansible.builtin.git:
      repo: '{{repo_url}}'
      dest: '{{dest_dir}}'